spring:
   datasource:
     url: jdbc:mysql://${MYSQL_SERVICE_HOST:mysql}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_DATABASE:test}
     username: ${MYSQL_USER:root}
     password: ${MYSQL_PASSWORD:password}
     testWhileIdle: true
     validationQuery: SELECT 1
   jpa:
      show-sql: true
      hibernate:
          ddl-auto: create
          dialect:  org.hibernate.dialect.MySQL5Dialect