spring:
   datasource:
     url: jdbc:mysql://mysql:3306/test
     username: ${MYSQL_USER:root}
     password: ${MYSQL_PASSWORD:password}
     testWhileIdle: true
     validationQuery: SELECT 1
   jpa:
      show-sql: true
      hibernate:
          ddl-auto: create
          dialect:  org.hibernate.dialect.MySQL5Dialect